"""external connections tables

Revision ID: 79b188889e30
Revises: 2a561e160fc0
Create Date: 2026-05-23 14:03:18.899590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '79b188889e30'
down_revision: Union[str, None] = '2a561e160fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('oauth_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.String(length=32), nullable=True),
    sa.Column('pat_token', sa.Text(), nullable=True),
    sa.Column('instance_url', sa.String(length=256), nullable=False),
    sa.Column('remote_username', sa.String(length=128), nullable=False),
    sa.Column('remote_user_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("provider IN ('github','gitea')", name='ck_conn_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_url', sa.String(length=512), nullable=False),
    sa.Column('external_repo', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_synced_at', sa.String(length=32), nullable=True),
    sa.Column('sync_direction', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("sync_direction IN ('bidirectional','import_only','export_only')", name='ck_ext_issue_direction'),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issues_processed', sa.Integer(), nullable=False),
    sa.Column('issues_created', sa.Integer(), nullable=False),
    sa.Column('issues_updated', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.CheckConstraint("direction IN ('import','export','bidirectional')", name='ck_sync_direction'),
    sa.CheckConstraint("status IN ('running','success','partial','failed')", name='ck_sync_status'),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    op.drop_table('external_issues')
    op.drop_table('external_connections')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
