"""milestones timers roles assignee-logs pr-links

Revision ID: a15a1fa9a7c3
Revises: 01731fcd0b00
Create Date: 2026-05-23 16:54:04.600868
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a15a1fa9a7c3"
down_revision: str | None = "01731fcd0b00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("due_date", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_project_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role"),
    )
    op.create_table(
        "issue_assignee_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("changed_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "time_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.String(length=32), nullable=True),
        sa.Column("stopped_at", sa.String(length=32), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("is_running", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("external_issues", sa.Column("link_type", sa.String(length=16), nullable=False))
    op.add_column(
        "external_issues", sa.Column("merged_status", sa.String(length=16), nullable=True)
    )
    op.add_column("issue_assignees", sa.Column("role", sa.String(length=32), nullable=True))
    with op.batch_alter_table("issues") as batch_op:
        batch_op.add_column(sa.Column("milestone_id", sa.String(length=36), nullable=True))
        batch_op.add_column(
            sa.Column("time_estimate_ms", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.create_foreign_key(
            "fk_issues_milestone", "milestones", ["milestone_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("time_estimate_ms")
        batch_op.drop_column("milestone_id")
    op.drop_column("issue_assignees", "role")
    op.drop_column("external_issues", "merged_status")
    op.drop_column("external_issues", "link_type")
    op.drop_table("time_entries")
    op.drop_table("issue_assignee_logs")
    op.drop_table("user_project_roles")
    op.drop_table("milestones")
    # ### end Alembic commands ###
